### ISSUE TITLE
Maybe fix bins in CNH Figure 2

### ISSUE THREAD

**Issue by chasehult** [chasehult/ISTA-131-Final-Project#5]
They're kinda messy.  Honestly, I don't 100% plan on doing this, but if this was an actual open source project, I would 100% write a ticket abt this bc the bins suck.  I need to find a better way to do a binned bar plot that isn't a histogram.

**Comment by RoyalDakat** [comment]
No worries mate, I was a little bit cheeky and I made the bins by checking the ranges of the data corresponding with a +=1 to the values in a dictionary. Which I they pushed into a series, which, I pushed into a bar graph. Its a bit of a wacky way to fudge the data and squeeze it back into a bar graph, but it does work. 
Kappa XD
-Arj
